using System.Xml.Serialization;

namespace DB
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub", IsNullable = false)]
    public partial class reportFile
    {

        private fileInformation fileInformationField;

        private record recordField;

        /// <remarks/>
        public fileInformation fileInformation
        {
            get
            {
                return this.fileInformationField;
            }
            set
            {
                this.fileInformationField = value;
            }
        }

        /// <remarks/>
        public record record
        {
            get
            {
                return this.recordField;
            }
            set
            {
                this.recordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class fileInformation
    {

        private string senderField;

        private string timestampField;

        private fileInformationEnvironment environmentField;

        private string versionField;

        /// <remarks/>
        public string sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }

        /// <remarks/>
        public string timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        public fileInformationEnvironment environment
        {
            get
            {
                return this.environmentField;
            }
            set
            {
                this.environmentField = value;
            }
        }

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum fileInformationEnvironment
    {

        /// <remarks/>
        SIM,

        /// <remarks/>
        PRO,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class partyCodeType
    {

        private object itemField;

        private ItemChoiceType7 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ALGO", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CLIENT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("INTC", typeof(partyCodeTypeINTC))]
        [System.Xml.Serialization.XmlElementAttribute("LEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("MIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_CCPT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_CONCAT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_DERCON", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_NIDN", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType7 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum partyCodeTypeINTC
    {

        /// <remarks/>
        INTC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub", IncludeInSchema = false)]
    public enum ItemChoiceType7
    {

        /// <remarks/>
        ALGO,

        /// <remarks/>
        CLIENT,

        /// <remarks/>
        INTC,

        /// <remarks/>
        LEI,

        /// <remarks/>
        MIC,

        /// <remarks/>
        NATIONAL_ID_CCPT,

        /// <remarks/>
        NATIONAL_ID_CONCAT,

        /// <remarks/>
        NATIONAL_ID_DERCON,

        /// <remarks/>
        NATIONAL_ID_NIDN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class referencePartyDetails
    {

        private LEId executingEntityIdField;

        private string internalPartyIdField;

        private partyCodeType codeField;

        private string branchCountryField;

        private string firstNameField;

        private string surnameField;

        private string birthdateField;

        /// <remarks/>
        public LEId executingEntityId
        {
            get
            {
                return this.executingEntityIdField;
            }
            set
            {
                this.executingEntityIdField = value;
            }
        }

        /// <remarks/>
        public string internalPartyId
        {
            get
            {
                return this.internalPartyIdField;
            }
            set
            {
                this.internalPartyIdField = value;
            }
        }

        /// <remarks/>
        public partyCodeType code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string branchCountry
        {
            get
            {
                return this.branchCountryField;
            }
            set
            {
                this.branchCountryField = value;
            }
        }

        /// <remarks/>
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }

        /// <remarks/>
        public string birthdate
        {
            get
            {
                return this.birthdateField;
            }
            set
            {
                this.birthdateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class LEId
    {

        private string lEIField;

        /// <remarks/>
        public string LEI
        {
            get
            {
                return this.lEIField;
            }
            set
            {
                this.lEIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class investmentExecutionId
    {

        private string itemField;

        private ItemChoiceType6 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ALGO", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CLIENT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("INTERNAL_PARTY_ID", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_CCPT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_CONCAT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_NIDN", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType6 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub", IncludeInSchema = false)]
    public enum ItemChoiceType6
    {

        /// <remarks/>
        ALGO,

        /// <remarks/>
        CLIENT,

        /// <remarks/>
        INTERNAL_PARTY_ID,

        /// <remarks/>
        NATIONAL_ID_CCPT,

        /// <remarks/>
        NATIONAL_ID_CONCAT,

        /// <remarks/>
        NATIONAL_ID_NIDN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class investmentDecisionId
    {

        private string itemField;

        private ItemChoiceType5 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ALGO", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("INTERNAL_PARTY_ID", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_CCPT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_CONCAT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_NIDN", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType5 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub", IncludeInSchema = false)]
    public enum ItemChoiceType5
    {

        /// <remarks/>
        ALGO,

        /// <remarks/>
        INTERNAL_PARTY_ID,

        /// <remarks/>
        NATIONAL_ID_CCPT,

        /// <remarks/>
        NATIONAL_ID_CONCAT,

        /// <remarks/>
        NATIONAL_ID_NIDN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirOtherDetails
    {

        private investmentDecisionId investmentDecisionIdField;

        private string investmentDecisionBranchCountryField;

        private investmentExecutionId executionIdField;

        private string supervisingBranchCountryField;

        private string waiverIndicatorField;

        private mifirOtherDetailsShortSellingIndicator shortSellingIndicatorField;

        private bool shortSellingIndicatorFieldSpecified;

        private string otcPostTradeIndicatorField;

        private YesNo commodityDerivativeIndicatorField;

        private bool commodityDerivativeIndicatorFieldSpecified;

        private YesNo sftrIndicatorField;

        private bool sftrIndicatorFieldSpecified;

        private mifirOtherDetailsClientType clientTypeField;

        private bool clientTypeFieldSpecified;

        private mifirOtherDetailsOrderType orderTypeField;

        private bool orderTypeFieldSpecified;

        private YesNo directedOrderFlagField;

        private bool directedOrderFlagFieldSpecified;

        private mifirOtherDetailsLiqpFlag liqpFlagField;

        private bool liqpFlagFieldSpecified;

        private string orderGroupIdField;

        private YesNo toaxFlagField;

        private bool toaxFlagFieldSpecified;

        /// <remarks/>
        public investmentDecisionId investmentDecisionId
        {
            get
            {
                return this.investmentDecisionIdField;
            }
            set
            {
                this.investmentDecisionIdField = value;
            }
        }

        /// <remarks/>
        public string investmentDecisionBranchCountry
        {
            get
            {
                return this.investmentDecisionBranchCountryField;
            }
            set
            {
                this.investmentDecisionBranchCountryField = value;
            }
        }

        /// <remarks/>
        public investmentExecutionId executionId
        {
            get
            {
                return this.executionIdField;
            }
            set
            {
                this.executionIdField = value;
            }
        }

        /// <remarks/>
        public string supervisingBranchCountry
        {
            get
            {
                return this.supervisingBranchCountryField;
            }
            set
            {
                this.supervisingBranchCountryField = value;
            }
        }

        /// <remarks/>
        public string waiverIndicator
        {
            get
            {
                return this.waiverIndicatorField;
            }
            set
            {
                this.waiverIndicatorField = value;
            }
        }

        /// <remarks/>
        public mifirOtherDetailsShortSellingIndicator shortSellingIndicator
        {
            get
            {
                return this.shortSellingIndicatorField;
            }
            set
            {
                this.shortSellingIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shortSellingIndicatorSpecified
        {
            get
            {
                return this.shortSellingIndicatorFieldSpecified;
            }
            set
            {
                this.shortSellingIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string otcPostTradeIndicator
        {
            get
            {
                return this.otcPostTradeIndicatorField;
            }
            set
            {
                this.otcPostTradeIndicatorField = value;
            }
        }

        /// <remarks/>
        public YesNo commodityDerivativeIndicator
        {
            get
            {
                return this.commodityDerivativeIndicatorField;
            }
            set
            {
                this.commodityDerivativeIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commodityDerivativeIndicatorSpecified
        {
            get
            {
                return this.commodityDerivativeIndicatorFieldSpecified;
            }
            set
            {
                this.commodityDerivativeIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public YesNo sftrIndicator
        {
            get
            {
                return this.sftrIndicatorField;
            }
            set
            {
                this.sftrIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sftrIndicatorSpecified
        {
            get
            {
                return this.sftrIndicatorFieldSpecified;
            }
            set
            {
                this.sftrIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public mifirOtherDetailsClientType clientType
        {
            get
            {
                return this.clientTypeField;
            }
            set
            {
                this.clientTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clientTypeSpecified
        {
            get
            {
                return this.clientTypeFieldSpecified;
            }
            set
            {
                this.clientTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public mifirOtherDetailsOrderType orderType
        {
            get
            {
                return this.orderTypeField;
            }
            set
            {
                this.orderTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderTypeSpecified
        {
            get
            {
                return this.orderTypeFieldSpecified;
            }
            set
            {
                this.orderTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public YesNo directedOrderFlag
        {
            get
            {
                return this.directedOrderFlagField;
            }
            set
            {
                this.directedOrderFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool directedOrderFlagSpecified
        {
            get
            {
                return this.directedOrderFlagFieldSpecified;
            }
            set
            {
                this.directedOrderFlagFieldSpecified = value;
            }
        }

        /// <remarks/>
        public mifirOtherDetailsLiqpFlag liqpFlag
        {
            get
            {
                return this.liqpFlagField;
            }
            set
            {
                this.liqpFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool liqpFlagSpecified
        {
            get
            {
                return this.liqpFlagFieldSpecified;
            }
            set
            {
                this.liqpFlagFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string orderGroupId
        {
            get
            {
                return this.orderGroupIdField;
            }
            set
            {
                this.orderGroupIdField = value;
            }
        }

        /// <remarks/>
        public YesNo toaxFlag
        {
            get
            {
                return this.toaxFlagField;
            }
            set
            {
                this.toaxFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toaxFlagSpecified
        {
            get
            {
                return this.toaxFlagFieldSpecified;
            }
            set
            {
                this.toaxFlagFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirOtherDetailsShortSellingIndicator
    {

        /// <remarks/>
        SESH,

        /// <remarks/>
        SSEX,

        /// <remarks/>
        SELL,

        /// <remarks/>
        UNDI,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum YesNo
    {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirOtherDetailsClientType
    {

        /// <remarks/>
        R,

        /// <remarks/>
        P,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(" ")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirOtherDetailsOrderType
    {

        /// <remarks/>
        P,

        /// <remarks/>
        A,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirOtherDetailsLiqpFlag
    {

        /// <remarks/>
        E,

        /// <remarks/>
        C,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirStrikePrice
    {

        private object itemField;

        private ItemChoiceType4 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BASIS_POINTS", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("MONETARY", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PERCENT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PNDG", typeof(mifirStrikePricePNDG))]
        [System.Xml.Serialization.XmlElementAttribute("YIELD", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType4 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirStrikePricePNDG
    {

        /// <remarks/>
        PNDG,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub", IncludeInSchema = false)]
    public enum ItemChoiceType4
    {

        /// <remarks/>
        BASIS_POINTS,

        /// <remarks/>
        MONETARY,

        /// <remarks/>
        PERCENT,

        /// <remarks/>
        PNDG,

        /// <remarks/>
        YIELD,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirUnderlyingIndexName
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("underlyingIndexNameAcronym", typeof(mifirUnderlyingIndexNameUnderlyingIndexNameAcronym))]
        [System.Xml.Serialization.XmlElementAttribute("underlyingIndexNameFull", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirUnderlyingIndexNameUnderlyingIndexNameAcronym
    {

        /// <remarks/>
        WIBO,

        /// <remarks/>
        TREA,

        /// <remarks/>
        TIBO,

        /// <remarks/>
        TLBO,

        /// <remarks/>
        SWAP,

        /// <remarks/>
        STBO,

        /// <remarks/>
        PRBO,

        /// <remarks/>
        PFAN,

        /// <remarks/>
        NIBO,

        /// <remarks/>
        MAAA,

        /// <remarks/>
        MOSP,

        /// <remarks/>
        LIBO,

        /// <remarks/>
        LIBI,

        /// <remarks/>
        JIBA,

        /// <remarks/>
        ISDA,

        /// <remarks/>
        GCFR,

        /// <remarks/>
        FUSW,

        /// <remarks/>
        EUCH,

        /// <remarks/>
        EUUS,

        /// <remarks/>
        EURI,

        /// <remarks/>
        EONS,

        /// <remarks/>
        EONA,

        /// <remarks/>
        CIBO,

        /// <remarks/>
        CDOR,

        /// <remarks/>
        BUBO,

        /// <remarks/>
        BBSW,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirUnderlyingIndex
    {

        private mifirUnderlyingIndexUnderlyingIndexDirection underlyingIndexDirectionField;

        private bool underlyingIndexDirectionFieldSpecified;

        private string underlyingIndexCodeField;

        private mifirUnderlyingIndexName underlyingIndexNameField;

        private string underlyingIndexTermField;

        private mifirUnderlyingIndexUnderlyingIndexTermUnit underlyingIndexTermUnitField;

        private bool underlyingIndexTermUnitFieldSpecified;

        /// <remarks/>
        public mifirUnderlyingIndexUnderlyingIndexDirection underlyingIndexDirection
        {
            get
            {
                return this.underlyingIndexDirectionField;
            }
            set
            {
                this.underlyingIndexDirectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool underlyingIndexDirectionSpecified
        {
            get
            {
                return this.underlyingIndexDirectionFieldSpecified;
            }
            set
            {
                this.underlyingIndexDirectionFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string underlyingIndexCode
        {
            get
            {
                return this.underlyingIndexCodeField;
            }
            set
            {
                this.underlyingIndexCodeField = value;
            }
        }

        /// <remarks/>
        public mifirUnderlyingIndexName underlyingIndexName
        {
            get
            {
                return this.underlyingIndexNameField;
            }
            set
            {
                this.underlyingIndexNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string underlyingIndexTerm
        {
            get
            {
                return this.underlyingIndexTermField;
            }
            set
            {
                this.underlyingIndexTermField = value;
            }
        }

        /// <remarks/>
        public mifirUnderlyingIndexUnderlyingIndexTermUnit underlyingIndexTermUnit
        {
            get
            {
                return this.underlyingIndexTermUnitField;
            }
            set
            {
                this.underlyingIndexTermUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool underlyingIndexTermUnitSpecified
        {
            get
            {
                return this.underlyingIndexTermUnitFieldSpecified;
            }
            set
            {
                this.underlyingIndexTermUnitFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirUnderlyingIndexUnderlyingIndexDirection
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("+")]
        Item,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirUnderlyingIndexUnderlyingIndexTermUnit
    {

        /// <remarks/>
        DAYS,

        /// <remarks/>
        WEEK,

        /// <remarks/>
        MNTH,

        /// <remarks/>
        YEAR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirUnderlyingInstrument
    {

        private mifirUnderlyingInstrumentUnderlyingInstrumentDirection underlyingInstrumentDirectionField;

        private bool underlyingInstrumentDirectionFieldSpecified;

        private string underlyingInstrumentCodeField;

        /// <remarks/>
        public mifirUnderlyingInstrumentUnderlyingInstrumentDirection underlyingInstrumentDirection
        {
            get
            {
                return this.underlyingInstrumentDirectionField;
            }
            set
            {
                this.underlyingInstrumentDirectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool underlyingInstrumentDirectionSpecified
        {
            get
            {
                return this.underlyingInstrumentDirectionFieldSpecified;
            }
            set
            {
                this.underlyingInstrumentDirectionFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string underlyingInstrumentCode
        {
            get
            {
                return this.underlyingInstrumentCodeField;
            }
            set
            {
                this.underlyingInstrumentCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirUnderlyingInstrumentUnderlyingInstrumentDirection
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("+")]
        Item,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirUnderlying
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("underlyingIndex", typeof(mifirUnderlyingIndex))]
        [System.Xml.Serialization.XmlElementAttribute("underlyingInstrument", typeof(mifirUnderlyingInstrument))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class instrumentId
    {

        private string iSINField;

        /// <remarks/>
        public string ISIN
        {
            get
            {
                return this.iSINField;
            }
            set
            {
                this.iSINField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirInstrumentDetails
    {

        private instrumentId instrumentIdField;

        private string instrumentNameField;

        private string instrumentClassField;

        private string notionalCurrency1Field;

        private string notionalCurrency2Field;

        private string priceMultiplierField;

        private mifirUnderlying[] underlyingField;

        private mifirInstrumentDetailsOptionType optionTypeField;

        private bool optionTypeFieldSpecified;

        private mifirStrikePrice strikePriceField;

        private string strikePriceCurrencyField;

        private mifirInstrumentDetailsOptionExerciseStyle optionExerciseStyleField;

        private bool optionExerciseStyleFieldSpecified;

        private string maturityDateInstrumentField;

        private string expiryDateField;

        private mifirInstrumentDetailsDeliveryType deliveryTypeField;

        private bool deliveryTypeFieldSpecified;

        /// <remarks/>
        public instrumentId instrumentId
        {
            get
            {
                return this.instrumentIdField;
            }
            set
            {
                this.instrumentIdField = value;
            }
        }

        /// <remarks/>
        public string instrumentName
        {
            get
            {
                return this.instrumentNameField;
            }
            set
            {
                this.instrumentNameField = value;
            }
        }

        /// <remarks/>
        public string instrumentClass
        {
            get
            {
                return this.instrumentClassField;
            }
            set
            {
                this.instrumentClassField = value;
            }
        }

        /// <remarks/>
        public string notionalCurrency1
        {
            get
            {
                return this.notionalCurrency1Field;
            }
            set
            {
                this.notionalCurrency1Field = value;
            }
        }

        /// <remarks/>
        public string notionalCurrency2
        {
            get
            {
                return this.notionalCurrency2Field;
            }
            set
            {
                this.notionalCurrency2Field = value;
            }
        }

        /// <remarks/>
        public string priceMultiplier
        {
            get
            {
                return this.priceMultiplierField;
            }
            set
            {
                this.priceMultiplierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("underlying")]
        public mifirUnderlying[] underlying
        {
            get
            {
                return this.underlyingField;
            }
            set
            {
                this.underlyingField = value;
            }
        }

        /// <remarks/>
        public mifirInstrumentDetailsOptionType optionType
        {
            get
            {
                return this.optionTypeField;
            }
            set
            {
                this.optionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optionTypeSpecified
        {
            get
            {
                return this.optionTypeFieldSpecified;
            }
            set
            {
                this.optionTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public mifirStrikePrice strikePrice
        {
            get
            {
                return this.strikePriceField;
            }
            set
            {
                this.strikePriceField = value;
            }
        }

        /// <remarks/>
        public string strikePriceCurrency
        {
            get
            {
                return this.strikePriceCurrencyField;
            }
            set
            {
                this.strikePriceCurrencyField = value;
            }
        }

        /// <remarks/>
        public mifirInstrumentDetailsOptionExerciseStyle optionExerciseStyle
        {
            get
            {
                return this.optionExerciseStyleField;
            }
            set
            {
                this.optionExerciseStyleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optionExerciseStyleSpecified
        {
            get
            {
                return this.optionExerciseStyleFieldSpecified;
            }
            set
            {
                this.optionExerciseStyleFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string maturityDateInstrument
        {
            get
            {
                return this.maturityDateInstrumentField;
            }
            set
            {
                this.maturityDateInstrumentField = value;
            }
        }

        /// <remarks/>
        public string expiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }

        /// <remarks/>
        public mifirInstrumentDetailsDeliveryType deliveryType
        {
            get
            {
                return this.deliveryTypeField;
            }
            set
            {
                this.deliveryTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveryTypeSpecified
        {
            get
            {
                return this.deliveryTypeFieldSpecified;
            }
            set
            {
                this.deliveryTypeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirInstrumentDetailsOptionType
    {

        /// <remarks/>
        PUTO,

        /// <remarks/>
        CALL,

        /// <remarks/>
        OTHR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirInstrumentDetailsOptionExerciseStyle
    {

        /// <remarks/>
        EURO,

        /// <remarks/>
        AMER,

        /// <remarks/>
        ASIA,

        /// <remarks/>
        BERM,

        /// <remarks/>
        OTHR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirInstrumentDetailsDeliveryType
    {

        /// <remarks/>
        PHYS,

        /// <remarks/>
        CASH,

        /// <remarks/>
        OPTL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirPrice
    {

        private object itemField;

        private ItemChoiceType3 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BASIS_POINTS", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("MONETARY", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NOAP", typeof(mifirPriceNOAP))]
        [System.Xml.Serialization.XmlElementAttribute("PERCENT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PNDG", typeof(mifirPricePNDG))]
        [System.Xml.Serialization.XmlElementAttribute("YIELD", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirPriceNOAP
    {

        /// <remarks/>
        NOAP,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirPricePNDG
    {

        /// <remarks/>
        PNDG,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub", IncludeInSchema = false)]
    public enum ItemChoiceType3
    {

        /// <remarks/>
        BASIS_POINTS,

        /// <remarks/>
        MONETARY,

        /// <remarks/>
        NOAP,

        /// <remarks/>
        PERCENT,

        /// <remarks/>
        PNDG,

        /// <remarks/>
        YIELD,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirQuantity
    {

        private string itemField;

        private ItemChoiceType2 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MONETARY", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NOMINAL", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("UNIT", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub", IncludeInSchema = false)]
    public enum ItemChoiceType2
    {

        /// <remarks/>
        MONETARY,

        /// <remarks/>
        NOMINAL,

        /// <remarks/>
        UNIT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirTransaction
    {

        private string trnRefNumberField;

        private string tradingVenueTrnIdCodeField;

        private string venueField;

        private string tradeTimeField;

        private mifirTransactionMifirTradingCapacity mifirTradingCapacityField;

        private bool mifirTradingCapacityFieldSpecified;

        private mifirQuantity quantityField;

        private string quantityCurrencyField;

        private mifirTransactionNotionalIncreaseDecrease notionalIncreaseDecreaseField;

        private bool notionalIncreaseDecreaseFieldSpecified;

        private mifirPrice priceField;

        private string priceCurrencyField;

        private string netAmountField;

        private string upfrontPaymentField;

        private string upfrontPaymentCurrencyField;

        private string complexTradeComponentIdField;

        /// <remarks/>
        public string trnRefNumber
        {
            get
            {
                return this.trnRefNumberField;
            }
            set
            {
                this.trnRefNumberField = value;
            }
        }

        /// <remarks/>
        public string tradingVenueTrnIdCode
        {
            get
            {
                return this.tradingVenueTrnIdCodeField;
            }
            set
            {
                this.tradingVenueTrnIdCodeField = value;
            }
        }

        /// <remarks/>
        public string venue
        {
            get
            {
                return this.venueField;
            }
            set
            {
                this.venueField = value;
            }
        }

        /// <remarks/>
        public string tradeTime
        {
            get
            {
                return this.tradeTimeField;
            }
            set
            {
                this.tradeTimeField = value;
            }
        }

        /// <remarks/>
        public mifirTransactionMifirTradingCapacity mifirTradingCapacity
        {
            get
            {
                return this.mifirTradingCapacityField;
            }
            set
            {
                this.mifirTradingCapacityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mifirTradingCapacitySpecified
        {
            get
            {
                return this.mifirTradingCapacityFieldSpecified;
            }
            set
            {
                this.mifirTradingCapacityFieldSpecified = value;
            }
        }

        /// <remarks/>
        public mifirQuantity quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public string quantityCurrency
        {
            get
            {
                return this.quantityCurrencyField;
            }
            set
            {
                this.quantityCurrencyField = value;
            }
        }

        /// <remarks/>
        public mifirTransactionNotionalIncreaseDecrease notionalIncreaseDecrease
        {
            get
            {
                return this.notionalIncreaseDecreaseField;
            }
            set
            {
                this.notionalIncreaseDecreaseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notionalIncreaseDecreaseSpecified
        {
            get
            {
                return this.notionalIncreaseDecreaseFieldSpecified;
            }
            set
            {
                this.notionalIncreaseDecreaseFieldSpecified = value;
            }
        }

        /// <remarks/>
        public mifirPrice price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        /// <remarks/>
        public string priceCurrency
        {
            get
            {
                return this.priceCurrencyField;
            }
            set
            {
                this.priceCurrencyField = value;
            }
        }

        /// <remarks/>
        public string netAmount
        {
            get
            {
                return this.netAmountField;
            }
            set
            {
                this.netAmountField = value;
            }
        }

        /// <remarks/>
        public string upfrontPayment
        {
            get
            {
                return this.upfrontPaymentField;
            }
            set
            {
                this.upfrontPaymentField = value;
            }
        }

        /// <remarks/>
        public string upfrontPaymentCurrency
        {
            get
            {
                return this.upfrontPaymentCurrencyField;
            }
            set
            {
                this.upfrontPaymentCurrencyField = value;
            }
        }

        /// <remarks/>
        public string complexTradeComponentId
        {
            get
            {
                return this.complexTradeComponentIdField;
            }
            set
            {
                this.complexTradeComponentIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirTransactionMifirTradingCapacity
    {

        /// <remarks/>
        DEAL,

        /// <remarks/>
        MTCH,

        /// <remarks/>
        AOTC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirTransactionNotionalIncreaseDecrease
    {

        /// <remarks/>
        INCR,

        /// <remarks/>
        DECR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirTransmission
    {

        private YesNo transmissionIdField;

        private bool transmissionIdFieldSpecified;

        private LEId transmittingEntityBuyerIdField;

        private LEId transmittingEntitySellerIdField;

        /// <remarks/>
        public YesNo transmissionId
        {
            get
            {
                return this.transmissionIdField;
            }
            set
            {
                this.transmissionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transmissionIdSpecified
        {
            get
            {
                return this.transmissionIdFieldSpecified;
            }
            set
            {
                this.transmissionIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        public LEId transmittingEntityBuyerId
        {
            get
            {
                return this.transmittingEntityBuyerIdField;
            }
            set
            {
                this.transmittingEntityBuyerIdField = value;
            }
        }

        /// <remarks/>
        public LEId transmittingEntitySellerId
        {
            get
            {
                return this.transmittingEntitySellerIdField;
            }
            set
            {
                this.transmittingEntitySellerIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirSellerDecisionMakerDetails
    {

        private buyerSellerDecisionMakerId sellerDecisionMakerIdField;

        private string sellerDecisionFirstnameField;

        private string sellerDecisionSurnameField;

        private string sellerDecisionBirthdateField;

        /// <remarks/>
        public buyerSellerDecisionMakerId sellerDecisionMakerId
        {
            get
            {
                return this.sellerDecisionMakerIdField;
            }
            set
            {
                this.sellerDecisionMakerIdField = value;
            }
        }

        /// <remarks/>
        public string sellerDecisionFirstname
        {
            get
            {
                return this.sellerDecisionFirstnameField;
            }
            set
            {
                this.sellerDecisionFirstnameField = value;
            }
        }

        /// <remarks/>
        public string sellerDecisionSurname
        {
            get
            {
                return this.sellerDecisionSurnameField;
            }
            set
            {
                this.sellerDecisionSurnameField = value;
            }
        }

        /// <remarks/>
        public string sellerDecisionBirthdate
        {
            get
            {
                return this.sellerDecisionBirthdateField;
            }
            set
            {
                this.sellerDecisionBirthdateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class buyerSellerDecisionMakerId
    {

        private string itemField;

        private ItemChoiceType1 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INTERNAL_PARTY_ID", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("LEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_CCPT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_CONCAT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_DERCON", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_NIDN", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub", IncludeInSchema = false)]
    public enum ItemChoiceType1
    {

        /// <remarks/>
        INTERNAL_PARTY_ID,

        /// <remarks/>
        LEI,

        /// <remarks/>
        NATIONAL_ID_CCPT,

        /// <remarks/>
        NATIONAL_ID_CONCAT,

        /// <remarks/>
        NATIONAL_ID_DERCON,

        /// <remarks/>
        NATIONAL_ID_NIDN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirSellerDetails
    {

        private buyerSellerId sellerIdField;

        private string sellerBranchCountryField;

        private string sellerFirstnameField;

        private string sellerSurnameField;

        private string sellerBirthdateField;

        /// <remarks/>
        public buyerSellerId sellerId
        {
            get
            {
                return this.sellerIdField;
            }
            set
            {
                this.sellerIdField = value;
            }
        }

        /// <remarks/>
        public string sellerBranchCountry
        {
            get
            {
                return this.sellerBranchCountryField;
            }
            set
            {
                this.sellerBranchCountryField = value;
            }
        }

        /// <remarks/>
        public string sellerFirstname
        {
            get
            {
                return this.sellerFirstnameField;
            }
            set
            {
                this.sellerFirstnameField = value;
            }
        }

        /// <remarks/>
        public string sellerSurname
        {
            get
            {
                return this.sellerSurnameField;
            }
            set
            {
                this.sellerSurnameField = value;
            }
        }

        /// <remarks/>
        public string sellerBirthdate
        {
            get
            {
                return this.sellerBirthdateField;
            }
            set
            {
                this.sellerBirthdateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class buyerSellerId
    {

        private object itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INTC", typeof(buyerSellerIdINTC))]
        [System.Xml.Serialization.XmlElementAttribute("INTERNAL_PARTY_ID", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("LEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("MIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_CCPT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_CONCAT", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_DERCON", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NATIONAL_ID_NIDN", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum buyerSellerIdINTC
    {

        /// <remarks/>
        INTC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        INTC,

        /// <remarks/>
        INTERNAL_PARTY_ID,

        /// <remarks/>
        LEI,

        /// <remarks/>
        MIC,

        /// <remarks/>
        NATIONAL_ID_CCPT,

        /// <remarks/>
        NATIONAL_ID_CONCAT,

        /// <remarks/>
        NATIONAL_ID_DERCON,

        /// <remarks/>
        NATIONAL_ID_NIDN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirSeller
    {

        private mifirSellerDetails[] mifirSellerDetailsField;

        private mifirSellerDecisionMakerDetails[] mifirSellerDecisionMakerDetailsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mifirSellerDetails")]
        public mifirSellerDetails[] mifirSellerDetails
        {
            get
            {
                return this.mifirSellerDetailsField;
            }
            set
            {
                this.mifirSellerDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mifirSellerDecisionMakerDetails")]
        public mifirSellerDecisionMakerDetails[] mifirSellerDecisionMakerDetails
        {
            get
            {
                return this.mifirSellerDecisionMakerDetailsField;
            }
            set
            {
                this.mifirSellerDecisionMakerDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirBuyerDecisionMakerDetails
    {

        private buyerSellerDecisionMakerId buyerDecisionMakerIdField;

        private string buyerDecisionFirstnameField;

        private string buyerDecisionSurnameField;

        private string buyerDecisionBirthdateField;

        /// <remarks/>
        public buyerSellerDecisionMakerId buyerDecisionMakerId
        {
            get
            {
                return this.buyerDecisionMakerIdField;
            }
            set
            {
                this.buyerDecisionMakerIdField = value;
            }
        }

        /// <remarks/>
        public string buyerDecisionFirstname
        {
            get
            {
                return this.buyerDecisionFirstnameField;
            }
            set
            {
                this.buyerDecisionFirstnameField = value;
            }
        }

        /// <remarks/>
        public string buyerDecisionSurname
        {
            get
            {
                return this.buyerDecisionSurnameField;
            }
            set
            {
                this.buyerDecisionSurnameField = value;
            }
        }

        /// <remarks/>
        public string buyerDecisionBirthdate
        {
            get
            {
                return this.buyerDecisionBirthdateField;
            }
            set
            {
                this.buyerDecisionBirthdateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirBuyerDetails
    {

        private buyerSellerId buyerIdField;

        private string buyerBranchCountryField;

        private string buyerFirstnameField;

        private string buyerSurnameField;

        private string buyerBirthdateField;

        /// <remarks/>
        public buyerSellerId buyerId
        {
            get
            {
                return this.buyerIdField;
            }
            set
            {
                this.buyerIdField = value;
            }
        }

        /// <remarks/>
        public string buyerBranchCountry
        {
            get
            {
                return this.buyerBranchCountryField;
            }
            set
            {
                this.buyerBranchCountryField = value;
            }
        }

        /// <remarks/>
        public string buyerFirstname
        {
            get
            {
                return this.buyerFirstnameField;
            }
            set
            {
                this.buyerFirstnameField = value;
            }
        }

        /// <remarks/>
        public string buyerSurname
        {
            get
            {
                return this.buyerSurnameField;
            }
            set
            {
                this.buyerSurnameField = value;
            }
        }

        /// <remarks/>
        public string buyerBirthdate
        {
            get
            {
                return this.buyerBirthdateField;
            }
            set
            {
                this.buyerBirthdateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirBuyer
    {

        private mifirBuyerDetails[] mifirBuyerDetailsField;

        private mifirBuyerDecisionMakerDetails[] mifirBuyerDecisionMakerDetailsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mifirBuyerDetails")]
        public mifirBuyerDetails[] mifirBuyerDetails
        {
            get
            {
                return this.mifirBuyerDetailsField;
            }
            set
            {
                this.mifirBuyerDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mifirBuyerDecisionMakerDetails")]
        public mifirBuyerDecisionMakerDetails[] mifirBuyerDecisionMakerDetails
        {
            get
            {
                return this.mifirBuyerDecisionMakerDetailsField;
            }
            set
            {
                this.mifirBuyerDecisionMakerDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirCounterpartyDetails
    {

        private LEId executingEntityIdField;

        private YesNo mifidInvestmentFirmField;

        private bool mifidInvestmentFirmFieldSpecified;

        private string branchMembershipCountryField;

        private mifirBuyer buyerField;

        private mifirSeller sellerField;

        /// <remarks/>
        public LEId executingEntityId
        {
            get
            {
                return this.executingEntityIdField;
            }
            set
            {
                this.executingEntityIdField = value;
            }
        }

        /// <remarks/>
        public YesNo mifidInvestmentFirm
        {
            get
            {
                return this.mifidInvestmentFirmField;
            }
            set
            {
                this.mifidInvestmentFirmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mifidInvestmentFirmSpecified
        {
            get
            {
                return this.mifidInvestmentFirmFieldSpecified;
            }
            set
            {
                this.mifidInvestmentFirmFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string branchMembershipCountry
        {
            get
            {
                return this.branchMembershipCountryField;
            }
            set
            {
                this.branchMembershipCountryField = value;
            }
        }

        /// <remarks/>
        public mifirBuyer buyer
        {
            get
            {
                return this.buyerField;
            }
            set
            {
                this.buyerField = value;
            }
        }

        /// <remarks/>
        public mifirSeller seller
        {
            get
            {
                return this.sellerField;
            }
            set
            {
                this.sellerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirDelegation
    {

        private mifirDelegationPartialAssistanceFlag partialAssistanceFlagField;

        private bool partialAssistanceFlagFieldSpecified;

        private string partialAssistanceSubmitterIdField;

        private string pairingIdField;

        /// <remarks/>
        public mifirDelegationPartialAssistanceFlag partialAssistanceFlag
        {
            get
            {
                return this.partialAssistanceFlagField;
            }
            set
            {
                this.partialAssistanceFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partialAssistanceFlagSpecified
        {
            get
            {
                return this.partialAssistanceFlagFieldSpecified;
            }
            set
            {
                this.partialAssistanceFlagFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string partialAssistanceSubmitterId
        {
            get
            {
                return this.partialAssistanceSubmitterIdField;
            }
            set
            {
                this.partialAssistanceSubmitterIdField = value;
            }
        }

        /// <remarks/>
        public string pairingId
        {
            get
            {
                return this.pairingIdField;
            }
            set
            {
                this.pairingIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum mifirDelegationPartialAssistanceFlag
    {

        /// <remarks/>
        Y,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class mifirDetails
    {

        private mifirDelegation delegationField;

        private mifirCounterpartyDetails counterpartyDetailsField;

        private mifirTransmission transmissionField;

        private mifirTransaction transactionDetailsField;

        private mifirInstrumentDetails instrumentDetailsField;

        private mifirOtherDetails otherDetailsField;

        /// <remarks/>
        public mifirDelegation delegation
        {
            get
            {
                return this.delegationField;
            }
            set
            {
                this.delegationField = value;
            }
        }

        /// <remarks/>
        public mifirCounterpartyDetails counterpartyDetails
        {
            get
            {
                return this.counterpartyDetailsField;
            }
            set
            {
                this.counterpartyDetailsField = value;
            }
        }

        /// <remarks/>
        public mifirTransmission transmission
        {
            get
            {
                return this.transmissionField;
            }
            set
            {
                this.transmissionField = value;
            }
        }

        /// <remarks/>
        public mifirTransaction transactionDetails
        {
            get
            {
                return this.transactionDetailsField;
            }
            set
            {
                this.transactionDetailsField = value;
            }
        }

        /// <remarks/>
        public mifirInstrumentDetails instrumentDetails
        {
            get
            {
                return this.instrumentDetailsField;
            }
            set
            {
                this.instrumentDetailsField = value;
            }
        }

        /// <remarks/>
        public mifirOtherDetails otherDetails
        {
            get
            {
                return this.otherDetailsField;
            }
            set
            {
                this.otherDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class configurableFields
    {

        private string userField1Field;

        private string userField2Field;

        private string userField3Field;

        private string userField4Field;

        private string userField5Field;

        private string userField6Field;

        private string userField7Field;

        private string userField8Field;

        private string userField9Field;

        /// <remarks/>
        public string userField1
        {
            get
            {
                return this.userField1Field;
            }
            set
            {
                this.userField1Field = value;
            }
        }

        /// <remarks/>
        public string userField2
        {
            get
            {
                return this.userField2Field;
            }
            set
            {
                this.userField2Field = value;
            }
        }

        /// <remarks/>
        public string userField3
        {
            get
            {
                return this.userField3Field;
            }
            set
            {
                this.userField3Field = value;
            }
        }

        /// <remarks/>
        public string userField4
        {
            get
            {
                return this.userField4Field;
            }
            set
            {
                this.userField4Field = value;
            }
        }

        /// <remarks/>
        public string userField5
        {
            get
            {
                return this.userField5Field;
            }
            set
            {
                this.userField5Field = value;
            }
        }

        /// <remarks/>
        public string userField6
        {
            get
            {
                return this.userField6Field;
            }
            set
            {
                this.userField6Field = value;
            }
        }

        /// <remarks/>
        public string userField7
        {
            get
            {
                return this.userField7Field;
            }
            set
            {
                this.userField7Field = value;
            }
        }

        /// <remarks/>
        public string userField8
        {
            get
            {
                return this.userField8Field;
            }
            set
            {
                this.userField8Field = value;
            }
        }

        /// <remarks/>
        public string userField9
        {
            get
            {
                return this.userField9Field;
            }
            set
            {
                this.userField9Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class processingDetails
    {

        private string tradeDateField;

        private string customerTransactionIdField;

        private processingDetailsActionType actionTypeField;

        private string businessUnitField;

        private string userIdField;

        private string commentField;

        private string modificationDateField;

        private string tradeReportIdField;

        private string sourceSystemField;

        private processingDetailsRecordMode recordModeField;

        private bool recordModeFieldSpecified;

        private string messageIDField;

        /// <remarks/>
        public string tradeDate
        {
            get
            {
                return this.tradeDateField;
            }
            set
            {
                this.tradeDateField = value;
            }
        }

        /// <remarks/>
        public string customerTransactionId
        {
            get
            {
                return this.customerTransactionIdField;
            }
            set
            {
                this.customerTransactionIdField = value;
            }
        }

        /// <remarks/>
        public processingDetailsActionType actionType
        {
            get
            {
                return this.actionTypeField;
            }
            set
            {
                this.actionTypeField = value;
            }
        }

        /// <remarks/>
        public string businessUnit
        {
            get
            {
                return this.businessUnitField;
            }
            set
            {
                this.businessUnitField = value;
            }
        }

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public string modificationDate
        {
            get
            {
                return this.modificationDateField;
            }
            set
            {
                this.modificationDateField = value;
            }
        }

        /// <remarks/>
        public string tradeReportId
        {
            get
            {
                return this.tradeReportIdField;
            }
            set
            {
                this.tradeReportIdField = value;
            }
        }

        /// <remarks/>
        public string sourceSystem
        {
            get
            {
                return this.sourceSystemField;
            }
            set
            {
                this.sourceSystemField = value;
            }
        }

        /// <remarks/>
        public processingDetailsRecordMode recordMode
        {
            get
            {
                return this.recordModeField;
            }
            set
            {
                this.recordModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recordModeSpecified
        {
            get
            {
                return this.recordModeFieldSpecified;
            }
            set
            {
                this.recordModeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string messageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum processingDetailsActionType
    {

        /// <remarks/>
        N,

        /// <remarks/>
        R,

        /// <remarks/>
        C,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public enum processingDetailsRecordMode
    {

        /// <remarks/>
        draft,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("check draft")]
        checkdraft,

        /// <remarks/>
        backreporting,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("assistance only")]
        assistanceonly,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class transactionPositionReport
    {

        private processingDetails processingDetailsField;

        private configurableFields configurableFieldsField;

        private mifirDetails mifirField;

        /// <remarks/>
        public processingDetails processingDetails
        {
            get
            {
                return this.processingDetailsField;
            }
            set
            {
                this.processingDetailsField = value;
            }
        }

        /// <remarks/>
        public configurableFields configurableFields
        {
            get
            {
                return this.configurableFieldsField;
            }
            set
            {
                this.configurableFieldsField = value;
            }
        }

        /// <remarks/>
        public mifirDetails mifir
        {
            get
            {
                return this.mifirField;
            }
            set
            {
                this.mifirField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://deutsche-boerse.com/DBRegHub")]
    public partial class record
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referencePartyDetails", typeof(referencePartyDetails))]
        [System.Xml.Serialization.XmlElementAttribute("transaction", typeof(transactionPositionReport))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }


}
